#!/bin/bash

# Set the location here. This has to be manually done on your machine.
# Make sure you are not using spaces or other special characters in your paths.

#lib_path="YOUR PATH TO MixMHCpred1.0/lib FOLDER"
lib_path="/Users/davidgfeller/Research/LICR/Research/Immunopeptidomics/Full_package_PLoSCompBio/MixMHCpred/source/MixMHCpred1.0/lib"


if [[ "$lib_path" =~ " " ]]; then
    echo Spaces in path to MixMHCpred are not supported
    echo Make sure you have set the correct path in MixMHCpred
    exit 1;
fi

if [ ! -f "$lib_path"/MixMHCpred.x ]; then
	echo MixMHCpred resources not found. Make sure you have set the correct path for lib_path in MixMHCpred file.
	exit 1;
fi


# Parse flags
while [ $# -gt 0 ]; do
	case $1 in
		-i | --input) input=$2; shift 2;;
		-o | --output) output_file=$2; shift 2;;
		-h | --allele) alleles=$2; shift 2;;
		*) shift 1;;
	esac
done

input=`perl -e 'use Cwd "abs_path";print abs_path(shift)' $input`;
if [[ "$input" =~ " " ]]; then
    echo Spaces in input path are not supported
    exit 1;
fi
if [ ! -f $input ]; then
	echo Missing input file
	exit 1;
fi

dir=$(pwd)
output_file=$dir/$output_file
if [[ "$input" =~ " " ]]; then
    echo Spaces in output path are not supported
    exit 1;
fi

perl $lib_path/run_MixMHCpred.pl --alleles $alleles --input $input --dir $dir --output $output_file --lib $lib_path
