#!/bin/bash

###############
# MixMHCpred is a predictor of HLA ligand displayed at the cell surface.
#
# MixMHCpred can be used freely by academic groups for non-commercial purposes (see license).
# The product is provided free of charge, and, therefore, on an "as is"
#  basis, without warranty of any kind.
#
# FOR-PROFIT USERS
# If you plan to use MixMHCpred (version 2.2) or any data provided with the script in any for-profit
# application, you are required to obtain a separate  license.
# To do so, please contact eauffarth@licr.org at the Ludwig Institute for Cancer Research Ltd.
#
# If you use MixMHCpred2.2 in a publication, please cite:
# Bassani-Sternberg M et al. Deciphering HLA motifs across HLA peptidomes improves neo-antigen predictions and identifies allostery regulating HLA specificity, PLoS Comp Bio (2017).
# and
# Gfeller et al. Improved predictions of immunogenicity reveal SARS-Cov-2 CD8 T-cell epitopes, BioRxiv (2022).
#
# For scientific questions, please contact David Gfeller (David.Gfeller@unil.ch)
#
# Copyright (2022) David Gfeller
###############

# Set the location here. This has to be manually done on your machine.
# Make sure you are not using spaces or other special characters in your paths.
lib_path="/app/MixMHCpred/lib"

#echo $lib_path

if [[ "$lib_path" =~ " " ]]; then
    echo Spaces in path to MixMHCpred are not supported
    echo Make sure you have set the correct path in MixMHCpred
    exit 1;
fi

if [ ! -f "$lib_path"/MixMHCpred.x ]; then
	echo MixMHCpred resources not found. Make sure you have set the correct path for lib_path in MixMHCpred file.
	exit 1;
fi

usage="Usage: MixMHCpred -i INPUT_FILE -o OUTPUT_FILE -h LIST_OF_ALLELES"


# Make sure the first line of the -h output is the version (used in PRIME)
if [[ "$1" == "--help" || "$1" == "-h" ]]; then
cat <<END
MixMHCpred2.2
$usage
Mandatory parameters:

  -i, --input             Absolute or relative path to the input file (fasta format or list of peptides)
  -o, --output            Name of the output file
  -a, --alleles           List of HLA alleles separated by commas (e.g., A0301,A2402,B1501,B3906,C0303,C0702)

END
	exit 0;
fi

# Parse flags
while [ $# -gt 0 ]; do
	case $1 in
		-i | --input) input=$2; shift 2;;
		-o | --output) output_file=$2; shift 2;;
		-a | --allele) alleles=$2; shift 2;;
		*) shift 1;;
	esac
done

input=`perl -e 'use Cwd "abs_path";print abs_path(shift)' $input`;
if [[ "$input" =~ " " ]]; then
    echo Spaces in input path are not supported
    exit 1;
fi
if [ ! -f $input ]; then
	echo Missing input file
	exit 1;
fi

if [ ! -n "$alleles" ]; then
	echo Missing alleles
	exit 1;
fi


echo "" > $output_file
output_file=`perl -e 'use Cwd "abs_path";print abs_path(shift)' $output_file`;
dir=$(pwd)

perl $lib_path/run_MixMHCpred.pl --alleles $alleles --input $input --dir $dir --output $output_file --lib $lib_path
